services:
  - type: web
    name: kodescruz-backend
    env: python
    region: oregon
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn main:app --workers 4 --worker-class uvicorn.workers.UvicornWorker --bind 0.0.0.0:$PORT
    envVars:
      - key: GROQ_API_KEY
        sync: false
      - key: SECRET_KEY
        generateValue: true
      - key: MODEL_NAME
        value: llama-3.3-70b-versatile
      - key: TEMPERATURE
        value: "0.7"
      - key: MAX_TOKENS
        value: "2000"
      - key: DEBUG
        value: "False"
      - key: LOG_LEVEL
        value: INFO
      - key: DATABASE_URL
        value: sqlite:///./kodescruz.db
      - key: ALLOWED_ORIGINS
        value: https://kodes-cruxx.vercel.app
        sync: false

    healthCheckPath: /health
    autoDeploy: true
